name: Set Telegram bot Daily routine

on:
  schedule:
    # 매주 월~금 오전 8:30 KST = 매일 23:30 UTC (주말 제외)
    - cron: '30 23 * * 1-5'
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run bot script
        run: python sendMessage.py